[Basic]
word = "citka"
language = "lojban"
dictionarydef = "x1 eats/ingests/consumes (transitive verb) x2"

[Basic.role]
position = 1
description = "consumer"

[Basic.role]
position = 2
description = "food"

[JustifyPrimitive]

[JustifyPrimitive.destinctConcept]
description = "ingest, take something inside body"

[JustifyPrimitive.destinctConcept]
description = "consume, destroy to consume resources"

[JustifyPrimitive.scalarVariation]
None

[JustifyPrimitive.bestConstruction]
None

[JustifyRoles]

[JustifyRoles.roleEssential]
position = 1
description = "need something to be consuming for eating to occur"

[JustifyRoles.roleEssental]
position = 2
description = "need some food to eat. Eating nothing is not eating"


