[Basic]
word = "citka"
language = "lojban"
dictionarydef = "x1 eats/ingests/consumes (transitive verb) x2"

[Basic.role]
position = 1
description = "consumer, resource consuming process"

[Basic.role]
position = 2
description = "food, fuel, resources"

[JustifyPrimitive]
scalar = false # not a scalar

[[JustifyPrimitive.destinctConcept]]
description = "ingest, take something inside body"
bestConstruct = ""

[[JustifyPrimitive.destinctConcept]]
description = "consume, destroy to absorb resources"
bestConstruct = ""

[JustifyRoles]

[[JustifyRoles.roleEssential]]
position = 1
description = "need something to be consuming for eating to occur"

[[JustifyRoles.roleEssental]]
position = 2
description = "need some food to eat. Eating nothing is not eating"

[[JustifyRoles.roleExcluded]]
description = "orifice, mouth, intake. A physical part of consumer."
